services:
  # Main application service
  - type: web
    name: cooking-mcp-app
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cooking-mcp-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: cooking-mcp-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: ENABLE_CORS
        value: true
      - key: API_V1_STR
        value: /api/v1
      - key: PROJECT_NAME
        value: MCP Cooking Lab Notebook
      - key: BACKEND_CORS_ORIGINS
        value: '["*"]'
      - key: GIT_AUTHOR_NAME
        value: "Lab Bot"
      - key: GIT_AUTHOR_EMAIL
        value: "lab@cooking-mcp.com"
      # Slack integration (add your tokens in Render dashboard)
      - key: SLACK_BOT_TOKEN
        sync: false  # Set manually in dashboard
      - key: SLACK_SIGNING_SECRET
        sync: false  # Set manually in dashboard
      # Optional notification services (configure as needed)
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_NUMBER
        sync: false
      - key: OPENAI_API_KEY
        sync: false

  # PostgreSQL database
  - type: pserv
    name: cooking-mcp-postgres
    plan: starter
    runtime: postgresql
    databases:
      - name: cooking_mcp
        user: cooking_user
    envVars:
      - key: POSTGRES_DB
        value: cooking_mcp
      - key: POSTGRES_USER
        value: cooking_user
      - key: POSTGRES_PASSWORD
        generateValue: true

  # Redis cache
  - type: redis
    name: cooking-mcp-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru